import { OfficialCardAnnotation } from '../types';

export const OFFICIAL_CARD_ANNOTATIONS: OfficialCardAnnotation[] = [
  // Major Arcana (大阿尔卡纳)
  { cardId: 'ar00', arcana: 'major', cardNumber: 0, numerology: '0 - 无限可能', planet: '天王星', zodiac: null, house: '第零宫', element: '风', uprightMeaning: '天真、可能性、自由、流浪、探险、纯真。代表一个新的开始，万事皆有可能。', reversedMeaning: '冒险、轻率、冲动、鲁莽、缺乏方向感。可能表示机会被浪费或决定过于草率。', keywords: ['冒险', '自由', '无限', '纯净', '可能'] },
  { cardId: 'ar01', arcana: 'major', cardNumber: 1, numerology: '1 - 创造力', planet: '水星', zodiac: null, house: '第一宫', element: '风', uprightMeaning: '意志力、创造力、自我表达、自信、领导力、技能、才华。象征着你拥有实现目标所需的一切资源。', reversedMeaning: '操纵、狡猾、欺骗、自私、浪费天赋。可能表示缺乏自信或资源被误用。', keywords: ['创造', '意志', '自信', '资源', '表达'] },
  { cardId: 'ar02', arcana: 'major', cardNumber: 2, numerology: '2 - 对立平衡', planet: '月亮', zodiac: null, house: '第二宫', element: '水', uprightMeaning: '直覺、神秘、內在世界、潛意識、女性本質、秘密。代表倾听内心的声音，拥抱未知。', reversedMeaning: '被動、消極、逃避現實、隱瞞、迷失。可能表示過度依賴直覺或隱瞞重要信息。', keywords: ['直覺', '神秘', '內在', '秘密', '女性'] },
  { cardId: 'ar03', arcana: 'major', cardNumber: 3, numerology: '3 - 丰盛', planet: '金星', zodiac: null, house: '第三宫', element: '土', uprightMeaning: '丰盛、富足、创造力、成长、繁荣、自然、艺术。代表生活各方面的充盈与美好。', reversedMeaning: '依赖、占有、停滞、过度保护。可能表示财务问题或创造力受阻。', keywords: ['丰盛', '富饶', '成长', '繁荣', '自然'] },
  { cardId: 'ar04', arcana: 'major', cardNumber: 4, numerology: '4 - 稳定', planet: null, zodiac: '白羊座', house: '第四宫', element: '火', uprightMeaning: '权威、领导力、稳定性、结构、父亲般的形象、决断力。代表建立稳固的基础和秩序。', reversedMeaning: '专制、僵化、缺乏弹性、控制欲。可能表示过于固执或权威被滥用。', keywords: ['权威', '稳定', '秩序', '决断', '领导'] },
  { cardId: 'ar05', arcana: 'major', cardNumber: 5, numerology: '5 - 信仰', planet: null, zodiac: '金牛座', house: '第五宫', element: '土', uprightMeaning: '慈悲、智慧、宽容、精神指导、传统、信念。代表寻求更高层次的指引和道德支持。', reversedMeaning: '限制、偏见、传统主义、伪善。可能表示信仰被扭曲或缺乏精神支持。', keywords: ['信仰', '智慧', '慈悲', '传统', '指引'] },
  { cardId: 'ar06', arcana: 'major', cardNumber: 6, numerology: '6 - 选择', planet: null, zodiac: '双子座', house: '第六宫', element: '风', uprightMeaning: '爱、美、选择、诱惑、价值观、和谐、沟通。代表在爱与诱惑之间做出选择。', reversedMeaning: '失衡、犹豫、困惑、价值观冲突。可能表示选择困难或关系失衡。', keywords: ['选择', '爱恋', '诱惑', '和谐', '价值'] },
  { cardId: 'ar07', arcana: 'major', cardNumber: 7, numerology: '7 - 意志力', planet: null, zodiac: '巨蟹座', house: '第七宫', element: '水', uprightMeaning: '胜利、意志力、决心、野心、自律、成功。象征着通过意志力克服障碍取得胜利。', reversedMeaning: '失去控制、侵略、冲动、急速行动。可能表示失去自律或过于急躁。', keywords: ['胜利', '意志', '决心', '野心', '成功'] },
  { cardId: 'ar08', arcana: 'major', cardNumber: 8, numerology: '8 - 勇气', planet: null, zodiac: '狮子座', house: '第八宫', element: '火', uprightMeaning: '勇气、耐心、慈悲、内心力量、坚韧、宽宏大量。代表着以温和的力量战胜困难。', reversedMeaning: '残忍、冲动、不耐烦、缺乏怜悯。可能表示内心力量被削弱或缺乏耐心。', keywords: ['勇气', '力量', '坚韧', '慈悲', '耐心'] },
  { cardId: 'ar09', arcana: 'major', cardNumber: 9, numerology: '9 - 智慧', planet: null, zodiac: '处女座', house: '第九宫', element: '土', uprightMeaning: '智慧、洞察力、内省、孤独、寻求真理、精神成长。代表通过独处和内省获得智慧。', reversedMeaning: '过度内省、孤立、傲慢、狭隘。可能表示过度自我批评或精神探索受阻。', keywords: ['智慧', '内省', '孤独', '洞察', '真理'] },
  { cardId: 'ar10', arcana: 'major', cardNumber: 10, numerology: '10 - 命运', planet: '木星', zodiac: null, house: '第十宫', element: '火', uprightMeaning: '命运、转变、连环、循环、运气、变革。代表着生命周期的自然循环和命运的转折。', reversedMeaning: '坏运气、停滞、命运逆转、意外改变。可能表示命运不佳或变革受阻。', keywords: ['命运', '转变', '循环', '运气', '变革'] },
  { cardId: 'ar11', arcana: 'major', cardNumber: 11, numerology: '11 - 正义', planet: null, zodiac: '天秤座', house: '第十一宫', element: '风', uprightMeaning: '正义、公平、诚实、道德、因果、真相。代表着行为的后果和正义的实现。', reversedMeaning: '不公、不诚实、法律问题、缺乏责任感。可能表示不公正或逃避责任。', keywords: ['正义', '公平', '因果', '诚实', '真相'] },
  { cardId: 'ar12', arcana: 'major', cardNumber: 12, numerology: '12 - 牺牲', planet: '海王星', zodiac: null, house: '第十二宫', element: '水', uprightMeaning: '停顿、牺牲、悬而未决、等待、预言、迷茫。代表着放下自我，接受更大的愿景。', reversedMeaning: '停滞、牺牲过多、优柔寡断、自怜。可能表示过度牺牲或方向迷失。', keywords: ['牺牲', '等待', '迷茫', '悬置', '放下'] },
  { cardId: 'ar13', arcana: 'major', cardNumber: 13, numerology: '13 - 结束', planet: null, zodiac: '天蝎座', house: '第八宫', element: '水', uprightMeaning: '结束、死亡、转变、腐朽、衰退、结束周期。代表着放下过去，拥抱新开始。', reversedMeaning: '抗拒结束、停滞不前、腐烂、腐烂的气息。可能表示害怕改变或无法放下过去。', keywords: ['结束', '死亡', '转变', '放下', '新生'] },
  { cardId: 'ar14', arcana: 'major', cardNumber: 14, numerology: '14 - 节制', planet: null, zodiac: '射手座', house: '第九宫', element: '火', uprightMeaning: '平衡、耐心、目的、节制、调节、协调。代表着不同力量的调和与平衡。', reversedMeaning: '失衡、过度、散漫、浪费、过度放纵。可能表示缺乏平衡或放纵无度。', keywords: ['平衡', '节制', '调和', '耐心', '协调'] },
  { cardId: 'ar15', arcana: 'major', cardNumber: 15, numerology: '15 - 黑暗', planet: null, zodiac: '摩羯座', house: '第十宫', element: '土', uprightMeaning: '依附、束缚、黑暗、物质主义、诱惑。代表着被物质或欲望所束缚。', reversedMeaning: '释放、自由、打破束缚、打破循环。可能表示摆脱束缚或看清诱惑的本质。', keywords: ['束缚', '欲望', '物质', '诱惑', '依附'] },
  { cardId: 'ar16', arcana: 'major', cardNumber: 16, numerology: '16 - 灾难', planet: '火星', zodiac: null, house: '第一宫', element: '火', uprightMeaning: '毁灭、动荡、突发事件、揭露、觉醒。代表着痛苦的变革带来新的开始。', reversedMeaning: '内部冲突、恐惧变化、预防、焦虑。可能表示害怕变革或内在动荡。', keywords: ['动荡', '毁灭', '突変', '觉醒', '启示'] },
  { cardId: 'ar17', arcana: 'major', cardNumber: 17, numerology: '17 - 希望', planet: null, zodiac: '水瓶座', house: '第十一宫', element: '风', uprightMeaning: '希望、信念、愿景、平安、和谐、灵感。代表着灵性的疗愈和希望的回归。', reversedMeaning: '绝望、失去信心、悲观、幻灭。可能表示失去希望或精神空虚。', keywords: ['希望', '信念', '疗愈', '灵性', '和谐'] },
  { cardId: 'ar18', arcana: 'major', cardNumber: 18, numerology: '18 - 幻象', planet: null, zodiac: '双鱼座', house: '第十二宫', element: '水', uprightMeaning: '幻象、恐惧、焦虑、潜意识、恐惧、欺骗。代表着面对内心的恐惧和不确定性。', reversedMeaning: '恐惧、焦虑、幻灭、潜意识的混乱。可能表示被恐惧支配或逃避现实。', keywords: ['幻象', '恐惧', '潜意识', '迷茫', '不安'] },
  { cardId: 'ar19', arcana: 'major', cardNumber: 19, numerology: '19 - 快乐', planet: '太阳', zodiac: null, house: '第五宫', element: '火', uprightMeaning: '快乐、成功、庆祝、正能量、活力、真理。代表着阳光般的喜悦和成功。', reversedMeaning: '悲伤、压抑、阴郁、成功反噬、虚假快乐。可能表示快乐被掩盖或短暂的满足。', keywords: ['快乐', '成功', '喜悦', '活力', '光明'] },
  { cardId: 'ar20', arcana: 'major', cardNumber: 20, numerology: '20 - 复活', planet: '冥王星', zodiac: null, house: '第十宫', element: '火', uprightMeaning: '审判、复活、更新、反思、觉醒、重生。代表着灵魂的觉醒和人生的重新开始。', reversedMeaning: '自我谴责、后悔、忽视、缺乏自省。可能表示逃避自我审视或拒绝改变。', keywords: ['审判', '重生', '觉醒', '反思', '更新'] },
  { cardId: 'ar21', arcana: 'major', cardNumber: 21, numerology: '21 - 完成', planet: '土星', zodiac: null, house: '第十宫', element: '土', uprightMeaning: '完成、整合、成就、成就感、整个人生、整体。代表着生命周期的圆满完成。', reversedMeaning: '不完整、失败、缺乏成就感、工作未完成。可能表示目标未达成或感觉空虚。', keywords: ['完成', '圆满', '成就', '整合', '整体'] },

  // Wands (权杖牌组 - 火)
  { cardId: 'waac', arcana: 'minor', suit: 'wands', cardNumber: 1, numerology: '1 - 创造力', planet: null, zodiac: null, house: '第一宫', element: '火', uprightMeaning: '创造力的爆发、新企业、精神灵感、欲望、勇气。代表着新的开始和蓬勃的创意能量。', reversedMeaning: '延迟、缺乏动力、创造力受阻、颓废。可能表示创意被压制或缺乏行动力。', keywords: ['创造', '欲望', '灵感', '开始', '热情'] },
  { cardId: 'wa02', arcana: 'minor', suit: 'wands', cardNumber: 2, numerology: '2 - 愿景', planet: '火星', zodiac: '白羊座', house: '第一宫', element: '火', uprightMeaning: '远见、领导力、发现、审视、决策、探索。代表着对未来的规划和愿景的建立。', reversedMeaning: '分歧、优柔寡断、缺乏远见、争吵。可能表示计划受阻或方向不明。', keywords: ['愿景', '规划', '领导', '决策', '探索'] },
  { cardId: 'wa03', arcana: 'minor', suit: 'wands', cardNumber: 3, numerology: '3 - 能量', planet: '太阳', zodiac: '白羊座', house: '第一宫', element: '火', uprightMeaning: '扩张、远见、娱乐、度假、冒险、社会。代表着自信的扩张和远大的目标。', reversedMeaning: '停滞、延迟、争论、失望。可能表示扩张受阻或过度自信。', keywords: ['扩张', '自信', '冒险', '成就', '远见'] },
  { cardId: 'wa04', arcana: 'minor', suit: 'wands', cardNumber: 4, numerology: '4 - 庆祝', planet: '金星', zodiac: '白羊座', house: '第一宫', element: '火', uprightMeaning: '和平、胜利、休息、庆祝、回归、繁荣。代表着工作之外的休息和庆祝。', reversedMeaning: '冲突、争吵、和平破裂、不和谐。可能表示庆祝被中断或不和。', keywords: ['庆祝', '和平', '胜利', '休息', '繁荣'] },
  { cardId: 'wa05', arcana: 'minor', suit: 'wands', cardNumber: 5, numerology: '5 - 竞争', planet: '土星', zodiac: '狮子座', house: '第五宫', element: '火', uprightMeaning: '竞争、冲突、冲突、挑衅、欺骗。代表着与他人竞争或内在的冲突。', reversedMeaning: '避免冲突、盗窃、输掉、失败。可能表示逃避竞争或处于劣势。', keywords: ['竞争', '冲突', '挑战', '对抗', '输赢'] },
  { cardId: 'wa06', arcana: 'minor', suit: 'wands', cardNumber: 6, numerology: '6 - 胜利', planet: '木星', zodiac: '狮子座', house: '第五宫', element: '火', uprightMeaning: '胜利、认可、成功、英雄主义、社会地位。代表着胜利和获得公众的认可。', reversedMeaning: '失败、批评、失败者、骄傲自大。可能表示胜利被夺走或过度自负。', keywords: ['胜利', '认可', '成功', '荣誉', '声望'] },
  { cardId: 'wa07', arcana: 'minor', suit: 'wands', cardNumber: 7, numerology: '7 - 挑战', planet: '火星', zodiac: '狮子座', house: '第五宫', element: '火', uprightMeaning: '挑战、冲突、防御、固执、竞争力。代表着面对挑战时的防御姿态。', reversedMeaning: '失败、夸夸其谈、逃避挑战、焦虑。可能表示无法应对挑战或被动攻击。', keywords: ['挑战', '防御', '对抗', '坚持', '意志'] },
  { cardId: 'wa08', arcana: 'minor', suit: 'wands', cardNumber: 8, numerology: '8 - 速度', planet: '水星', zodiac: '射手座', house: '第九宫', element: '火', uprightMeaning: '行动、速度、欲望、快速行动、旅行、精神。代表着快速移动和新的方向。', reversedMeaning: '等待、延迟、挫折、慢速。可能表示延迟或方向受阻。', keywords: ['速度', '行动', '迅速', '旅行', '方向'] },
  { cardId: 'wa09', arcana: 'minor', suit: 'wands', cardNumber: 9, numerology: '9 - 坚韧', planet: '月亮', zodiac: '射手座', house: '第九宫', element: '火', uprightMeaning: '力量、勇气、坚定、恐惧、持久力、耐心。代表着在逆境中保持坚韧。', reversedMeaning: '疲劳、筋疲力尽、过度谨慎、偏执狂。可能表示精力耗尽或恐惧阻碍行动。', keywords: ['坚韧', '耐心', '勇气', '坚持', '防御'] },
  { cardId: 'wa10', arcana: 'minor', suit: 'wands', cardNumber: 10, numerology: '10 - 负担', planet: '土星', zodiac: '射手座', house: '第九宫', element: '火', uprightMeaning: '责任、压力、负担、工作、挣扎、权力。代表着沉重的责任和压力。', reversedMeaning: '过度劳累、倦怠、无法应付、压力过重。可能表示压力过大或责任被转移。', keywords: ['压力', '责任', '负担', '辛劳', '权力'] },
  { cardId: 'wapa', arcana: 'minor', suit: 'wands', cardNumber: null, courtNumber: 11, numerology: null, planet: null, zodiac: null, house: '第一宫', element: '火', uprightMeaning: '灵感、消息、创造、好奇心、探索。代表着年轻的活力和新的创意灵感。', reversedMeaning: '传播八卦、坏消息、焦虑、停滞。可能表示消息延迟或缺乏方向。', keywords: ['创意', '好奇', '探索', '消息', '灵感'] },
  { cardId: 'wakn', arcana: 'minor', suit: 'wands', cardNumber: null, courtNumber: 12, numerology: null, planet: null, zodiac: '射手座', house: '第九宫', element: '火', uprightMeaning: '能量、热情、勇气、冒险、冲动、自信。代表着充满激情的行动者。', reversedMeaning: '冲动、鲁莽、傲慢、失去控制、愤怒。可能表示行动过于冲动或愤怒失控。', keywords: ['激情', '勇敢', '冲动', '行动', '自信'] },
  { cardId: 'waqu', arcana: 'minor', suit: 'wands', cardNumber: null, courtNumber: 13, numerology: null, planet: null, zodiac: '白羊座', house: '第一宫', element: '火', uprightMeaning: '温暖、活力、自信、慷慨、魅力、活力。代表着温暖而有影响力的女性能量。', reversedMeaning: '愤怒、报复心强、苛刻、泼冷水。可能表示热情被削减或关系中的冲突。', keywords: ['温暖', '自信', '魅力', '慷慨', '活力'] },
  { cardId: 'waki', arcana: 'minor', suit: 'wands', cardNumber: null, courtNumber: 14, numerology: null, planet: null, zodiac: '狮子座', house: '第五宫', element: '火', uprightMeaning: '领导力、愿景、权威、企业家精神、统治、愿景。代表着成功的领导者和愿景家。', reversedMeaning: '过度扩张、暴君、冲动、判断失误、严厉。可能表示领导过度或控制欲过强。', keywords: ['领导', '愿景', '权威', '创业', '统治'] },

  // Cups (圣杯牌组 - 水)
  { cardId: 'cuac', arcana: 'minor', suit: 'cups', cardNumber: 1, numerology: '1 - 情感', planet: null, zodiac: null, house: '第四宫', element: '水', uprightMeaning: '爱、幸福、情感、新开始、灵性、满足。代表着爱的满溢和新情感的萌芽。', reversedMeaning: '情感空虚、孤独、失落、悲伤、压抑。可能表示情感封闭或失落感。', keywords: ['爱', '情感', '满足', '灵性', '新开始'] },
  { cardId: 'cu02', arcana: 'minor', suit: 'cups', cardNumber: 2, numerology: '2 - 结合', planet: '金星', zodiac: '巨蟹座', house: '第四宫', element: '水', uprightMeaning: '爱、和谐、伙伴关系、吸引力、团结、情感。代表着爱情的结合和伙伴关系。', reversedMeaning: '不平衡、诱惑、欺骗、不和谐、诱惑。可能表示关系不平衡或诱惑的考验。', keywords: ['爱情', '结合', '和谐', '伙伴', '吸引'] },
  { cardId: 'cu03', arcana: 'minor', suit: 'cups', cardNumber: 3, numerology: '3 - 庆祝', planet: '木星', zodiac: '巨蟹座', house: '第四宫', element: '水', uprightMeaning: '庆祝、友谊、创造力、情感表达、欢乐、社会。代表着友谊的欢乐和群体的庆祝。', reversedMeaning: '过度、过度放纵、孤立、后悔、庆祝过度。可能表示过度沉溺或社交过度。', keywords: ['友谊', '庆祝', '欢乐', '群体', '创造'] },
  { cardId: 'cu04', arcana: 'minor', suit: 'cups', cardNumber: 4, numerology: '4 - 倦怠', planet: '月亮', zodiac: '巨蟹座', house: '第四宫', element: '水', uprightMeaning: '倦怠、忧郁、冷漠、梦境、逃避、回顾过去。代表着对现状的厌倦和对过去的沉溺。', reversedMeaning: '新视角、觉醒、灵感、复兴、行动。可能表示即将从倦怠中苏醒。', keywords: ['倦怠', '忧郁', '梦境', '逃避', '回顾'] },
  { cardId: 'cu05', arcana: 'minor', suit: 'cups', cardNumber: 5, numerology: '5 - 损失', planet: '火星', zodiac: '天蝎座', house: '第八宫', element: '水', uprightMeaning: '损失、遗憾、悲伤、失望、悲伤、怨恨。代表着接受失去后的感恩。', reversedMeaning: '接受、释放过去、宽恕、感恩、和平。可能表示放下遗憾或找到新的希望。', keywords: ['损失', '遗憾', '悲伤', '失望', '感恩'] },
  { cardId: 'cu06', arcana: 'minor', suit: 'cups', cardNumber: 6, numerology: '6 - 怀旧', planet: '太阳', zodiac: '天蝎座', house: '第八宫', element: '水', uprightMeaning: '怀旧、回忆、快乐过往、纯真、童年、回归。代表着对过去的美好回忆和纯真时光。', reversedMeaning: '无法放下过去、创伤、幼稚、幻灭。可能表示沉溺于过去或幻灭感。', keywords: ['怀旧', '回忆', '纯真', '童年', '过去'] },
  { cardId: 'cu07', arcana: 'minor', suit: 'cups', cardNumber: 7, numerology: '7 - 选择', planet: '金星', zodiac: '天蝎座', house: '第八宫', element: '水', uprightMeaning: '幻想、选择、幻象、梦想、欲望、诱惑。代表着面对多个诱惑和选择。', reversedMeaning: '缺乏清晰度、被诱惑、混乱、误导、虚假承诺。可能表示选择困难或被幻象迷惑。', keywords: ['选择', '幻想', '幻象', '诱惑', '梦想'] },
  { cardId: 'cu08', arcana: 'minor', suit: 'cups', cardNumber: 8, numerology: '8 - 离开', planet: '土星', zodiac: '双鱼座', house: '第十二宫', element: '水', uprightMeaning: '放弃、离开、寻找意义、撤退、遗弃、渴望。代表着为了更深的意义而离开。', reversedMeaning: '不忠、逃避、浪费时间、无方向、渴望。可能表示逃避责任或无法离开。', keywords: ['离开', '放弃', '寻找', '撤退', '渴望'] },
  { cardId: 'cu09', arcana: 'minor', suit: 'cups', cardNumber: 9, numerology: '9 - 愿望', planet: '木星', zodiac: '双鱼座', house: '第十二宫', element: '水', uprightMeaning: '满足、幸福、情感满足、愿望成真、快乐、喜悦。代表着愿望即将实现。', reversedMeaning: '不满意、失眠、贪婪、物欲、不满足。可能表示欲望无法满足或过度追求物质。', keywords: ['愿望', '满足', '快乐', '幸福', '喜悦'] },
  { cardId: 'cu10', arcana: 'minor', suit: 'cups', cardNumber: 10, numerology: '10 - 幸福', planet: '火星', zodiac: '双鱼座', house: '第十二宫', element: '水', uprightMeaning: '幸福、家庭团聚、和谐、爱情、情感满足、繁荣。代表着家庭和情感的圆满。', reversedMeaning: '家庭冲突、破碎的家庭、失去家庭纽带、不和谐。可能表示家庭问题或情感破裂。', keywords: ['幸福', '家庭', '和谐', '爱', '圆满'] },
  { cardId: 'cupa', arcana: 'minor', suit: 'cups', cardNumber: null, courtNumber: 11, numerology: null, planet: null, zodiac: null, house: '第四宫', element: '水', uprightMeaning: '想象、好奇、同情、创造力、情绪化的消息。代表着敏感而富有想象力的年轻能量。', reversedMeaning: '情绪波动、担心、空想、过度情绪化。可能表示情绪不稳定或过度敏感。', keywords: ['想象', '好奇', '同情', '创造', '敏感'] },
  { cardId: 'cukn', arcana: 'minor', suit: 'cups', cardNumber: null, courtNumber: 12, numerology: null, planet: null, zodiac: '双鱼座', house: '第十二宫', element: '水', uprightMeaning: '理想主义、浪漫、艺术追求、敏感、魅力。代表着浪漫而富有艺术气质的追求者。', reversedMeaning: '情绪化、过度浪漫、冷漠、不切实际。可能表示过于浪漫或不切实际。', keywords: ['浪漫', '理想', '艺术', '敏感', '追求'] },
  { cardId: 'cuqu', arcana: 'minor', suit: 'cups', cardNumber: null, courtNumber: 13, numerology: null, planet: null, zodiac: '巨蟹座', house: '第四宫', element: '水', uprightMeaning: '同理心、敏感、关怀、直觉、情感成熟、滋养。代表着充满同理心和关怀的女性能量。', reversedMeaning: '情绪过度、过度依赖、情绪化、占有欲。可能表示情绪过于敏感或依赖他人。', keywords: ['同理', '关怀', '直觉', '滋养', '成熟'] },
  { cardId: 'cuki', arcana: 'minor', suit: 'cups', cardNumber: null, courtNumber: 14, numerology: null, planet: null, zodiac: '天蝎座', house: '第八宫', element: '水', uprightMeaning: '宽宏大量、仁慈、平衡、同情心、智慧、领导力。代表着情感成熟而平衡的领导者。', reversedMeaning: '情感压抑、冷漠、过度严厉、情绪波动。可能表示情感控制过度或冷漠。', keywords: ['宽宏', '仁慈', '平衡', '智慧', '领导'] },

  // Swords (宝剑牌组 - 风)
  { cardId: 'swac', arcana: 'minor', suit: 'swords', cardNumber: 1, numerology: '1 - 思维', planet: null, zodiac: null, house: '第七宫', element: '风', uprightMeaning: '突破、新想法、清晰、锐利、力量、真相。代表着清晰的思想和突破性的洞察。', reversedMeaning: '混乱、困惑、愤怒、暴力、破坏。可能表示思维混乱或冲突激烈。', keywords: ['思维', '清晰', '突破', '真相', '力量'] },
  { cardId: 'sw02', arcana: 'minor', suit: 'swords', cardNumber: 2, numerology: '2 - 决定', planet: '月亮', zodiac: '天秤座', house: '第七宫', element: '风', uprightMeaning: '困难决定、优柔寡断、僵局、平衡、中立。代表着需要做出艰难的选择。', reversedMeaning: '优柔寡断、无法决定、混乱、心碎。可能表示选择困难或决定被推迟。', keywords: ['决定', '选择', '平衡', '纠结', '中立'] },
  { cardId: 'sw03', arcana: 'minor', suit: 'swords', cardNumber: 3, numerology: '3 - 心碎', planet: '土星', zodiac: '天秤座', house: '第七宫', element: '风', uprightMeaning: '心碎、悲伤、失落、痛苦、眼泪、悲伤。代表着情感的伤害和失落。', reversedMeaning: '治愈、原谅、接受、继续前进、恢复。可能表示正在愈合或需要放下。', keywords: ['心碎', '悲伤', '失落', '痛苦', '眼泪'] },
  { cardId: 'sw04', arcana: 'minor', suit: 'swords', cardNumber: 4, numerology: '4 - 休息', planet: '木星', zodiac: '天秤座', house: '第七宫', element: '风', uprightMeaning: '休息、恢复、孤独、退缩、冥想、暂停。代表着从世界中退出休息。', reversedMeaning: '疲惫、精疲力竭、倦怠、强迫劳动。可能表示无法休息或过度劳累。', keywords: ['休息', '恢复', '冥想', '暂停', '独处'] },
  { cardId: 'sw05', arcana: 'minor', suit: 'swords', cardNumber: 5, numerology: '5 - 失败', planet: '金星', zodiac: '水瓶座', house: '第十一宫', element: '风', uprightMeaning: '失败、输掉、错误、冲突、失去、劣势。代表着内在或外在的冲突导致失败。', reversedMeaning: '重新开始、克服失败、寻求和平、接受失败。可能表示从失败中学习或重新开始。', keywords: ['失败', '冲突', '劣势', '失去', '错误'] },
  { cardId: 'sw06', arcana: 'minor', suit: 'swords', cardNumber: 6, numerology: '6 - 过渡', planet: '水星', zodiac: '水瓶座', house: '第十一宫', element: '风', uprightMeaning: '过渡、改变、离开、前进、旅行、出发。代表着生命的过渡期和新的旅程。', reversedMeaning: '犹豫不决、停滞、延迟、取消、无法前进。可能表示旅程延迟或方向不明。', keywords: ['过渡', '改变', '旅行', '离开', '前进'] },
  { cardId: 'sw07', arcana: 'minor', suit: 'swords', cardNumber: 7, numerology: '7 - 欺骗', planet: '月亮', zodiac: '水瓶座', house: '第十一宫', element: '风', uprightMeaning: '欺骗、策略、小偷、秘密、阴谋、狡猾。代表着通过狡猾的手段获取利益。', reversedMeaning: '被揭露、间谍、背叛、诚实、自知之明。可能表示被欺骗或需要看清真相。', keywords: ['欺骗', '策略', '秘密', '阴谋', '狡猾'] },
  { cardId: 'sw08', arcana: 'minor', suit: 'swords', cardNumber: 8, numerology: '8 - 限制', planet: '木星', zodiac: '双子座', house: '第三宫', element: '风', uprightMeaning: '限制、监禁、困难、问题、禁锢、束缚。代表着被困住的感觉和内在的限制。', reversedMeaning: '自由、释放、开放、新观点、解放。可能表示即将获得自由或打破限制。', keywords: ['限制', '监禁', '束缚', '困难', '困境'] },
  { cardId: 'sw09', arcana: 'minor', suit: 'swords', cardNumber: 9, numerology: '9 - 焦虑', planet: '火星', zodiac: '双子座', house: '第三宫', element: '风', uprightMeaning: '焦虑、恐惧、噩梦、担忧、压力、失眠。代表着深深的恐惧和担忧。', reversedMeaning: '希望、走出困境、面对恐惧、释放、内疚。可能表示需要面对恐惧才能解脱。', keywords: ['焦虑', '恐惧', '噩梦', '压力', '担忧'] },
  { cardId: 'sw10', arcana: 'minor', suit: 'swords', cardNumber: 10, numerology: '10 - 毁灭', planet: '太阳', zodiac: '双子座', house: '第三宫', element: '风', uprightMeaning: '毁灭、崩溃、痛苦、背叛、损失、创伤。代表着彻底的身心崩溃。', reversedMeaning: '开始新的篇章、慢慢重建、恢复、治愈、放下。可能表示最坏的已经过去，开始恢复。', keywords: ['毁灭', '崩溃', '创伤', '损失', '背叛'] },
  { cardId: 'swpa', arcana: 'minor', suit: 'swords', cardNumber: null, courtNumber: 11, numerology: null, planet: null, zodiac: null, house: '第七宫', element: '风', uprightMeaning: '好奇心、智力、沟通、学习、技巧、监视。代表着好奇而善于思考的年轻人。', reversedMeaning: '心不在焉、尴尬、矛盾心理、轻率、欺骗。可能表示思维混乱或表达不当。', keywords: ['好奇', '智慧', '沟通', '学习', '技巧'] },
  { cardId: 'swkn', arcana: 'minor', suit: 'swords', cardNumber: null, courtNumber: 12, numerology: null, planet: null, zodiac: '双子座', house: '第三宫', element: '风', uprightMeaning: '野心、行动、热情、欲望、勇敢、冲动。代表着充满热情和野心的行动者。', reversedMeaning: '冲动、轻率、不诚实、愤怒、残酷。可能表示行动过于冲动或缺乏诚信。', keywords: ['野心', '行动', '热情', '勇敢', '冲动'] },
  { cardId: 'swqu', arcana: 'minor', suit: 'swords', cardNumber: null, courtNumber: 13, numerology: null, planet: null, zodiac: '天秤座', house: '第七宫', element: '风', uprightMeaning: '智慧、同理心、清晰、洞察力、公平、真理。代表着智慧而公正的女性能量。', reversedMeaning: '残酷、冷漠、恶意、过度批评、刻薄。可能表示过于严苛或缺乏同理心。', keywords: ['智慧', '洞察', '公平', '清晰', '真理'] },
  { cardId: 'swki', arcana: 'minor', suit: 'swords', cardNumber: null, courtNumber: 14, numerology: null, planet: null, zodiac: '水瓶座', house: '第十一宫', element: '风', uprightMeaning: '智慧、理性、头脑清晰、权力、真理、不公平。代表着理性而强大的领导者。', reversedMeaning: '不公正、滥用权力、残忍、不诚实、偏执。可能表示权力被滥用或缺乏公正。', keywords: ['智慧', '理性', '权力', '公正', '真理'] },

  // Pentacles (星币牌组 - 土)
  { cardId: 'peac', arcana: 'minor', suit: 'pentacles', cardNumber: 1, numerology: '1 - 机会', planet: null, zodiac: null, house: '第十宫', element: '土', uprightMeaning: '新机会、繁荣、运气、丰盛、慷慨。代表着物质世界的新开始。', reversedMeaning: '错失机会、贪婪、贫穷、浪费、不感恩。可能表示机会被错过或过于贪婪。', keywords: ['机会', '繁荣', '丰盛', '幸运', '开始'] },
  { cardId: 'pe02', arcana: 'minor', suit: 'pentacles', cardNumber: 2, numerology: '2 - 适应', planet: '木星', zodiac: '摩羯座', house: '第十宫', element: '土', uprightMeaning: '适应、多任务处理、优先排序、资源分配、平衡。代表着在多个领域之间平衡资源。', reversedMeaning: '过度扩张、优先级混乱、财务不平衡、拖延。可能表示过于分散或优先级错误。', keywords: ['适应', '平衡', '多任务', '资源', '优先'] },
  { cardId: 'pe03', arcana: 'minor', suit: 'pentacles', cardNumber: 3, numerology: '3 - 技能', planet: '火星', zodiac: '摩羯座', house: '第十宫', element: '土', uprightMeaning: '团队合作、技能、工艺、工作、成就、协作。代表着技能和团队合作带来的成就。', reversedMeaning: '缺乏团队精神、个人主义、冲突、失败的努力。可能表示团队问题或技能不足。', keywords: ['技能', '合作', '工作', '成就', '团队'] },
  { cardId: 'pe04', arcana: 'minor', suit: 'pentacles', cardNumber: 4, numerology: '4 - 安全', planet: '太阳', zodiac: '摩羯座', house: '第十宫', element: '土', uprightMeaning: '安全、保守、执着、占有欲、财富、贪婪。代表着对物质财富的执着。', reversedMeaning: '慷慨、浪费、花钱如流水、开放、放手。可能表示过度执着或过于挥霍。', keywords: ['安全', '保守', '占有', '财富', '执着'] },
  { cardId: 'pe05', arcana: 'minor', suit: 'pentacles', cardNumber: 5, numerology: '5 - 需求', planet: '水星', zodiac: '金牛座', house: '第二宫', element: '土', uprightMeaning: '需求、经济困难、孤独、分离、物质需要。代表着物质匮乏和生存的需求。', reversedMeaning: '慈善、援助、捐助、精神援助、恢复。可能表示获得帮助或转向精神层面。', keywords: ['需求', '困难', '孤独', '分离', '匮乏'] },
  { cardId: 'pe06', arcana: 'minor', suit: 'pentacles', cardNumber: 6, numerology: '6 - 给予', planet: '月亮', zodiac: '金牛座', house: '第二宫', element: '土', uprightMeaning: '给予、慈善、分享、平衡、慷慨、循环。代表着给予和接受的平衡。', reversedMeaning: '不平等、贪婪、自私、债务、索取。可能表示给予不均或过于自私。', keywords: ['给予', '慈善', '慷慨', '平衡', '分享'] },
  { cardId: 'pe07', arcana: 'minor', suit: 'pentacles', cardNumber: 7, numerology: '7 - 耐心', planet: '土星', zodiac: '金牛座', house: '第二宫', element: '土', uprightMeaning: '耐心、专注、回报、长期投资、技能发展、奖励。代表着长期耕耘和等待回报。', reversedMeaning: '不耐烦、缺乏回报、失败的投资、停滞。可能表示等待无果或急于求成。', keywords: ['耐心', '专注', '投资', '等待', '回报'] },
  { cardId: 'pe08', arcana: 'minor', suit: 'pentacles', cardNumber: 8, numerology: '8 - 质量', planet: '太阳', zodiac: '处女座', house: '第六宫', element: '土', uprightMeaning: '品质、承诺、技能、奉献、追求卓越、专业知识。代表着对完美的追求和专业技能。', reversedMeaning: '缺乏专注、完美主义、缺乏努力、低标准。可能表示缺乏专业精神或过于追求完美。', keywords: ['品质', '技能', '专注', '专业', '追求'] },
  { cardId: 'pe09', arcana: 'minor', suit: 'pentacles', cardNumber: 9, numerology: '9 - 丰富', planet: '金星', zodiac: '处女座', house: '第六宫', element: '土', uprightMeaning: '丰富、繁荣、独立、自我充实、享受、自给自足。代表着物质上的丰富和自我满足。', reversedMeaning: '过度依赖、过度工作、倦怠、依赖他人、欺骗。可能表示过度依赖或工作过度。', keywords: ['丰富', '繁荣', '独立', '享受', '自足'] },
  { cardId: 'pe10', arcana: 'minor', suit: 'pentacles', cardNumber: 10, numerology: '10 - 财富', planet: '水星', zodiac: '处女座', house: '第六宫', element: '土', uprightMeaning: '财富、遗产、繁荣、家庭、传统、责任。代表着家族传承和物质上的成功。', reversedMeaning: '金钱问题、遗产纠纷、损失、责任过重、债务。可能表示财务问题或家庭纷争。', keywords: ['财富', '遗产', '家族', '传统', '繁荣'] },
  { cardId: 'pepa', arcana: 'minor', suit: 'pentacles', cardNumber: null, courtNumber: 11, numerology: null, planet: null, zodiac: null, house: '第十宫', element: '土', uprightMeaning: '野心、学习、技巧、新发展、成就、职业。代表着有抱负的年轻人和职业发展。', reversedMeaning: '浪费时间、缺乏方向、延迟学业、心不在焉。可能表示学业延迟或缺乏方向。', keywords: ['抱负', '学习', '技巧', '职业', '发展'] },
  { cardId: 'pekn', arcana: 'minor', suit: 'pentacles', cardNumber: null, courtNumber: 12, numerology: null, planet: null, zodiac: '处女座', house: '第六宫', element: '土', uprightMeaning: '实用、稳定、耐心、传统、商业、勤奋。代表着可靠而勤奋的工作者。', reversedMeaning: '无聊、停滞、懈怠、倦怠、缺乏动力。可能表示工作停滞或缺乏动力。', keywords: ['实用', '稳定', '勤奋', '传统', '耐心'] },
  { cardId: 'pequ', arcana: 'minor', suit: 'pentacles', cardNumber: null, courtNumber: 13, numerology: null, planet: null, zodiac: '摩羯座', house: '第十宫', element: '土', uprightMeaning: '富足、繁荣、务实、独立、热情、给予。代表着富足而独立的女性能量。', reversedMeaning: '过度物质化、贪婪、嫉妒、浪费、过度依赖。可能表示过于物质或嫉妒他人。', keywords: ['富足', '务实', '独立', '热情', '给予'] },
  { cardId: 'peki', arcana: 'minor', suit: 'pentacles', cardNumber: null, courtNumber: 14, numerology: null, planet: null, zodiac: '金牛座', house: '第二宫', element: '土', uprightMeaning: '成功、繁荣、商业头脑、领导力、权力、物质安全。代表着成功的商业领袖。', reversedMeaning: '贪婪、物质主义、浪费、自负、滥用职权。可能表示成功被金钱腐蚀或滥用权力。', keywords: ['成功', '繁荣', '权力', '领导', '商业'] },
];

export function getAnnotationByCardId(cardId: string): OfficialCardAnnotation | undefined {
  return OFFICIAL_CARD_ANNOTATIONS.find(a => a.cardId === cardId);
}

export function getAnnotationsByArcana(arcana: 'major' | 'minor'): OfficialCardAnnotation[] {
  return OFFICIAL_CARD_ANNOTATIONS.filter(a => a.arcana === arcana);
}

export function getAnnotationsBySuit(suit: 'wands' | 'cups' | 'swords' | 'pentacles'): OfficialCardAnnotation[] {
  return OFFICIAL_CARD_ANNOTATIONS.filter(a => a.suit === suit);
}

export function getCourtCards(): OfficialCardAnnotation[] {
  return OFFICIAL_CARD_ANNOTATIONS.filter(a => a.courtNumber !== undefined);
}

export function getNumberedCards(): OfficialCardAnnotation[] {
  return OFFICIAL_CARD_ANNOTATIONS.filter(a => a.cardNumber !== null && a.cardNumber !== undefined && !a.courtNumber);
}
